# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-11 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('birth', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
