# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-17 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[(1, '男'), (2, '女')], max_length=32)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
    ]
