# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-27 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20181126_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='beili',
            field=models.IntegerField(default=1000),
        ),
    ]
